name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VPS_USER_NAME: ${{ secrets.VPS_USER_NAME }}
      VPS_SERVER_NAME: ${{ secrets.VPS_SERVER_NAME }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: "12.x"

      - name: Check environment variables
        run: |
          echo "VPS_USER_NAME=$VPS_USER_NAME"
          echo "VPS_SERVER_NAME=$VPS_SERVER_NAME"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install rsync openssh-client -y

      - name: Setup SSH key
        run: |
          mkdir -p "$HOME/.ssh"
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
          ssh-keyscan ${{ secrets.VPS_SERVER_NAME }} >> "$HOME/.ssh/known_hosts"

      - name: Deploy via Rsync
        run: |
          rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . $VPS_USER_NAME@$VPS_SERVER_NAME:/var/www/apps/github/backend_itmo_test

      - name: Build and Deploy on Server
        run: |
          ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no $VPS_USER_NAME@$VPS_SERVER_NAME 'cd /var/www/apps/github/backend_itmo_test && docker compose up -d --build'
